[project]
name = "repo-docs"
version = "1.0.0"
description = "Documentation for Sports Intelligence Cookbooks."
authors = [
    { name = "NVIDIA Corporation" },
]
readme = "README.md"
requires-python = ">=3.10,<4"

dependencies = [
    # OSRB https://nvbugs/4819923
    "docutils",
    # OSRB https://nvbugs/4819936
    "certifi",
    # OSRB https://nvbugs/4819946
    "typing-extensions",
    # OSRB https://nvbugs/4820044
    "Sphinx",
    "nvidia-sphinx-theme",
    "myst-parser",
    "breathe",
    "sphinxcontrib-mermaid==0.9.2",  # v1.0.0 has an incompatiblity
    "sphinxemoji",
    "sphinx-design",
    "sphinxcontrib-youtube",
    "autodocsumm",
    "sphinx-autobuild",
    "sphinx-copybutton",
    "sphinxcontrib-bibtex",
    # OSRB https://nvbugspro.nvidia.com/bug/5296940
    "sphinx-sitemap",
    # OSRB https://nvbugspro.nvidia.com/bug/5934236
    "sphinx-last-updated-by-git",
]

[project.urls]
Repository = "https://github.com/NVIDIA/sports-intelligence-cookbooks"

[tool.uv]
managed = true
fork-strategy = "fewest"

[tool.hatch.build.targets.sdist]
include = ["doc_build_toolchain/repo/docs"]

[tool.hatch.build.targets.wheel]
include = ["doc_build_toolchain/repo/docs"]

[tool.hatch.build.targets.wheel.sources]
"doc_build_toolchain/repo/docs" = "docs"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
